//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindred.Knect.ITAT.Web {
    
    public partial class TemplateList {
        protected System.Web.UI.HtmlControls.HtmlGenericControl htmlBody;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.UserControl itatHeader;
        protected System.Web.UI.WebControls.DropDownList ddlShowFilter;
        protected System.Web.UI.WebControls.Button btnAdd;
        protected System.Web.UI.WebControls.Panel pnlGridHeader;
        protected System.Web.UI.WebControls.Panel pnlGridBody;
        protected Kindred.Common.Controls.KindredGridView grdTemplateList;
    }
}
