//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindred.Knect.ITAT.Web {
    
    public partial class TemplateWorkflows {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlGenericControl htmlBody;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.UserControl header;
        protected System.Web.UI.WebControls.Button btnAddWorkflow;
        protected System.Web.UI.WebControls.ImageButton btnWorkflowMoveUp;
        protected System.Web.UI.WebControls.ImageButton btnWorkflowMoveDown;
        protected System.Web.UI.WebControls.Panel pnlWorkflowGridHeader;
        protected System.Web.UI.WebControls.Panel pnlWorkflowGridBody;
        protected Kindred.Common.Controls.KindredGridView grdWorkflow;
        protected System.Web.UI.WebControls.Button btnAddDependency;
        protected System.Web.UI.WebControls.ImageButton btnDependencyMoveUp;
        protected System.Web.UI.WebControls.ImageButton btnDependencyMoveDown;
        protected System.Web.UI.WebControls.Panel pnlDependencyGridHeader;
        protected System.Web.UI.WebControls.Panel pnlDependencyGridBody;
        protected Kindred.Common.Controls.KindredGridView grdDependency;
    }
}
