//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kindred.Knect.ITAT.Web {
    
    public partial class TermDelete {
        protected System.Web.UI.HtmlControls.HtmlGenericControl body;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.UserControl header;
        protected System.Web.UI.WebControls.Panel editBody;
        protected System.Web.UI.WebControls.Label lblItemName1;
        protected System.Web.UI.WebControls.Label lblItemName2;
        protected System.Web.UI.WebControls.Button btnYes;
        protected System.Web.UI.WebControls.Button btnNo;
    }
}
