//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace Kindred.Knect.ITAT.LexmarkImaging.ItatServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ImagingSoap", Namespace="http://kindredhealthcare.com/")]
    public partial class Imaging : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidateManagedItemNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback StoreDocumentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Imaging() {
            this.Url = global::Kindred.Knect.ITAT.LexmarkImaging.Properties.Settings.Default.Kindred_Knect_ITAT_LexmarkImaging_ItatImagingWS_Imaging1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateManagedItemNumberCompletedEventHandler ValidateManagedItemNumberCompleted;
        
        /// <remarks/>
        public event StoreDocumentCompletedEventHandler StoreDocumentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://kindredhealthcare.com/ValidateManagedItemNumber", RequestNamespace="http://kindredhealthcare.com/", ResponseNamespace="http://kindredhealthcare.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidateManagedItemNumber(System.Guid systemId, string managedItemNumber) {
            object[] results = this.Invoke("ValidateManagedItemNumber", new object[] {
                        systemId,
                        managedItemNumber});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateManagedItemNumberAsync(System.Guid systemId, string managedItemNumber) {
            this.ValidateManagedItemNumberAsync(systemId, managedItemNumber, null);
        }
        
        /// <remarks/>
        public void ValidateManagedItemNumberAsync(System.Guid systemId, string managedItemNumber, object userState) {
            if ((this.ValidateManagedItemNumberOperationCompleted == null)) {
                this.ValidateManagedItemNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateManagedItemNumberOperationCompleted);
            }
            this.InvokeAsync("ValidateManagedItemNumber", new object[] {
                        systemId,
                        managedItemNumber}, this.ValidateManagedItemNumberOperationCompleted, userState);
        }
        
        private void OnValidateManagedItemNumberOperationCompleted(object arg) {
            if ((this.ValidateManagedItemNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateManagedItemNumberCompleted(this, new ValidateManagedItemNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://kindredhealthcare.com/StoreDocument", RequestNamespace="http://kindredhealthcare.com/", ResponseNamespace="http://kindredhealthcare.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string StoreDocument(System.Guid systemId, string managedItemNumber, string filePath) {
            object[] results = this.Invoke("StoreDocument", new object[] {
                        systemId,
                        managedItemNumber,
                        filePath});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void StoreDocumentAsync(System.Guid systemId, string managedItemNumber, string filePath) {
            this.StoreDocumentAsync(systemId, managedItemNumber, filePath, null);
        }
        
        /// <remarks/>
        public void StoreDocumentAsync(System.Guid systemId, string managedItemNumber, string filePath, object userState) {
            if ((this.StoreDocumentOperationCompleted == null)) {
                this.StoreDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStoreDocumentOperationCompleted);
            }
            this.InvokeAsync("StoreDocument", new object[] {
                        systemId,
                        managedItemNumber,
                        filePath}, this.StoreDocumentOperationCompleted, userState);
        }
        
        private void OnStoreDocumentOperationCompleted(object arg) {
            if ((this.StoreDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StoreDocumentCompleted(this, new StoreDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ValidateManagedItemNumberCompletedEventHandler(object sender, ValidateManagedItemNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateManagedItemNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateManagedItemNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void StoreDocumentCompletedEventHandler(object sender, StoreDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StoreDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StoreDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591