name: Elusive Software (GK.COM)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: [ web/elusivesoftware/ElusiveSoftware.net/**, windows/elusivesoftware/GloryKidd.WebCore/** ]
    
concurrency: 
  group: gk-${{ github.ref }}

jobs:
  build:
    name: Start Elusive Software Build
    runs-on: [ self-hosted ] 
    environment: Release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Generate Build Number
        id: buildid
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 0
          format: 'YYYY.MM.DD-HH.mm'
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
#      - name: Install dependencies
#        run: |
#          nuget restore web/elusivesoftware/ElusiveSoftware.sln
#      - name: Build Solution
#        run: |
#          msbuild web/elusivesoftware/ElusiveSoftware.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      - name: Output Values
        run: |
          echo "The value is set as ${{ vars.ELUSIVE_VERSION }}.${{ github.RUN_NUMBER }}"
#      - name: Upload Build Artifact
#        uses: actions/upload-artifact@v2.2.4
#        with:
#          name: GKWeb Build - ${{ steps.buildid.outputs.time }}
#          path: web/elusivesoftware/ElusiveSoftware.net/bin/app.publish/*
#          retention-days: 30
