name: Secure Documents (AISSWEB.COM)

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: [ web/SDTPortal/** ]
    
concurrency: 
  group: aisweb-${{ github.ref }}

jobs:
  sdt-build:
    name: Start Secure Document Portal Build
    runs-on: [ windows-latest ] 
    environment: Release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Generate Build Number
        id: buildid
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 0
          format: 'YYYY.MM.DD-HH.mm'
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Install dependencies
        run: |
          nuget restore web/SDTPortal/SDTPortal.sln
      - name: Build Solution
        run: |
          msbuild web/SDTPortal/SDTPortal.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: SDTPortal Build - ${{ steps.buildid.outputs.time }}
          path: web/SDTPortal/SDTPortal/bin/app.publish/*
          retention-days: 30

  aisweb-build:
    name: Start AISWeb Build
    runs-on: [ windows-latest ] 
    environment: Release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Generate Build Number
        id: buildid
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 0
          format: 'YYYY.MM.DD-HH.mm'
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.3
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Install dependencies
        run: |
          nuget restore web/SDTPortal/AISWeb.sln
      - name: Build Solution
        run: |
          msbuild web/SDTPortal/AISWeb.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: SDTPortal Build - ${{ steps.buildid.outputs.time }}
          path: web/SDTPortal/AISWeb/bin/app.publish/*
          retention-days: 30
